name: cajian
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nim_sdk_util:
    path: ./nim_sdk_util
  wx_sdk:
    path: ./wx_sdk

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.2
  crypto: ^2.0.6
  shared_preferences: ^0.5.3+4
  azlistview: ^0.1.2
  lpinyin: ^1.0.7
  # firebase_storage: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/login_bg@2x.png
   - images/login_logo_cajian@2x.png
   - images/login_with_wechat@2x.png
   - images/login_with_phone@2x.png
   - images/login_with_pwd@2x.png
   - images/icon_setting_collect@2x.png
   - images/icon_setting_MFWallet_recommend@2x.png
   - images/icon_setting_MFWallet@2x.png
   - images/icon_setting_wx@2x.png
   - images/icon_settings_about@2x.png
   - images/icon_settings_alipay@2x.png
   - images/icon_settings_general@2x.png
   - images/icon_settings_scan@2x.png
   - images/icon_settings_paycode@2x.png
   - images/icon_setting_service@2x.png
   - images/icon_setting_copy_contacts@2x.png
   - images/icon_settings_gray_qr@2x.png
   - images/icon_contact_groupchat@2x.png
   - images/icon_contact_newfriend@2x.png
   - images/icon_contact_phone@2x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
